### ISSUE TITLE
How experimental do u consider this?

### ISSUE THREAD

**Issue by darrencruse** [rjsmith/nk-graalvm#1]
Hi thanks for writing this I pulled it down yesterday and I was able to follow your instructions it did work for me.

(I had an endpoint written in rhino javascript that I switched over to your graalvm javascript and changed the code to use modern es6 javascript - const/let/destructuring/etc. - so fun!!)

My question:

I have a little NetKernel experience from almost 10 years ago - but I'm brand new to GraalVM.  When you titled this an "experiment" I assume you were discouraging people from using this in production right?  Can you say more about the risk how far you think/hope it is from being production worthy?

(i.e. is it more that GraalVM is still considered very new or more that your NetKernel module code here is very new and unproven?  maybe both?)

Thanks,

Darren

**Comment by rjsmith** [comment]
Hi. Thanks for your interest.
Please see LICENSE for warranty info (TL;DR is there is none).

**Comment by darrencruse** [comment]
Ha!  I love it!!  :)

I'd be disappointed if there was warranty info as I know your next breath would be "and here take a look at our very affordable options you can pay on our convenient monthly installment plan..." ;)
